<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
   <head>
      <link rel="stylesheet" type="text/css" href="style.css"/>
   </head>
   <body>
      <img style="position:absolute;top:1.58in;left:1.04in;width:6.93in;height:0.01in" src="ci_3.png" />
      <img style="position:absolute;top:1.60in;left:1.04in;width:6.93in;height:0.01in" src="ci_4.png" />
      <img style="position:absolute;top:1.58in;left:1.04in;width:0.01in;height:0.03in" src="ci_5.png" />
      <img style="position:absolute;top:1.58in;left:7.96in;width:0.01in;height:0.03in" src="ci_6.png" />
      <img style="position:absolute;top:0.65in;left:1.06in;width:1.25in;height:0.82in" src="ri_3.png" />
      <div style="position:absolute;top:0.73in;left:2.33in;width:3.49in;line-height:0.15in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Times;color:#000000">MINISTÉRIO DA EDUCAÇÃO</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Times;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Times;color:#000000">CENTRO FEDERAL DE EDUCAÇÃO TECNOLÓGICA DE</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Times;color:#000000"> </span><br/><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Times;color:#000000">MINAS GERAIS</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Times;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Times;color:#000000">SISTEMA INTEGRADO DE PATRIMÔNIO,</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Times;color:#000000"> </span><br/><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Times;color:#000000">ADMINISTRAÇÃO E CONTRATOS</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Times;color:#000000"> </span><br/></SPAN></div>
      <div style="position:absolute;top:1.03in;left:6.15in;width:1.85in;line-height:0.17in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Times;color:#000000">FOLHA DE ASSINATURAS</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Times;color:#000000"> </span><br/></SPAN></div>
      <div style="position:absolute;top:1.72in;left:6.61in;width:1.40in;line-height:0.16in;"><span style="font-style:italic;font-weight:normal;font-size:9pt;font-family:Times;color:#000000">Emitido em 15/05/2019</span><span style="font-style:italic;font-weight:normal;font-size:9pt;font-family:Times;color:#000000"> </span><br/></SPAN></div>
      <div style="position:absolute;top:2.21in;left:2.87in;width:3.27in;line-height:0.17in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Times;color:#000000">DECLARAÇÃO Nº 332/2019 - DECMCV (11.59.04)</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Times;color:#000000"> </span><br/></SPAN></div>
      <div style="position:absolute;top:2.55in;left:3.17in;width:2.71in;line-height:0.17in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Times;color:#000000">(Nº do Protocolo: NÃO PROTOCOLADO)</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Times;color:#000000"> </span><br/></SPAN></div>
      <div style="position:absolute;top:3.58in;left:3.14in;width:2.79in;line-height:0.16in;">
         <span style="font-style:italic;font-weight:normal;font-size:9pt;font-family:Times;color:#000000">(Assinado digitalmente em 31/05/2019 12:18 )</span><span style="font-style:italic;font-weight:normal;font-size:9pt;font-family:Times;color:#000000"> </span><br/>
         <DIV style="position:relative; left:0.39in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Times;color:#000000">SERGIO CAMPOS DE FREITAS</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Times;color:#000000"> </span><br/></SPAN></DIV>
      </div>
      <div style="position:absolute;top:3.92in;left:3.33in;width:2.43in;line-height:0.12in;"><span style="font-style:italic;font-weight:normal;font-size:7pt;font-family:Times;color:#000000">PROFESSOR ENS BASICO TECN TECNOLOGICO</span><span style="font-style:italic;font-weight:normal;font-size:7pt;font-family:Times;color:#000000"> </span><br/></SPAN></div>
      <div style="position:absolute;top:4.08in;left:4.05in;width:1.00in;line-height:0.12in;"><span style="font-style:italic;font-weight:normal;font-size:7pt;font-family:Times;color:#000000">DECMCV (11.59.04)</span><span style="font-style:italic;font-weight:normal;font-size:7pt;font-family:Times;color:#000000"> </span><br/></SPAN></div>
      <div style="position:absolute;top:4.25in;left:4.04in;width:1.00in;line-height:0.12in;"><span style="font-style:italic;font-weight:normal;font-size:7pt;font-family:Times;color:#000000">Matrícula: ###866#8</span><span style="font-style:italic;font-weight:normal;font-size:7pt;font-family:Times;color:#000000"> </span><br/></SPAN></div>
      <div style="position:absolute;top:5.40in;left:1.09in;width:2.08in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Times;color:#000000">Visualize o documento original em</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Times;color:#000000"> </span><br/></SPAN></div>
      <div style="position:absolute;top:5.40in;left:5.19in;width:1.50in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Times;color:#000000"> informando seu número:</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Times;color:#000000"> </span><br/></SPAN></div>
      <div style="position:absolute;top:5.40in;left:6.91in;width:0.36in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Times;color:#000000">, ano:</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Times;color:#000000"> </span><br/></SPAN></div>
      <div style="position:absolute;top:5.40in;left:7.56in;width:0.38in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Times;color:#000000">, tipo:</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Times;color:#000000"> </span><br/></SPAN></div>
      <a href="https://sig.cefetmg.br/public/jsp/autenticidade/form.jsf"><img style="position:absolute;top:5.51in;left:3.17in;width:2.02in;height:0.01in" src="ci_7.png" />
      </a>
      <div style="position:absolute;top:5.40in;left:3.17in;width:2.06in;line-height:0.16in;"><a href="https://sig.cefetmg.br/public/jsp/autenticidade/form.jsf"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Times;color:#0000ff">https://sig.cefetmg.br/documentos/</span></a>
         <span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Times;color:#0000ff"> </span><br/></SPAN>
      </div>
      <div style="position:absolute;top:5.40in;left:1.98in;width:5.09in;line-height:0.17in;">
         <DIV style="position:relative; left:4.71in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Times;color:#000000">332</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Times;color:#000000"> </span><br/></DIV>
         <span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Times;color:#000000">DECLARAÇÃO</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Times;color:#000000">, data de emissão: </span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Times;color:#000000">31/05/2019</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Times;color:#000000"> e o código de verificação: </span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Times;color:#000000">70f2374dc5</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Times;color:#000000"> </span><br/></SPAN>
      </div>
      <div style="position:absolute;top:5.40in;left:7.27in;width:0.33in;line-height:0.17in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Times;color:#000000">2019</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Times;color:#000000"> </span><br/></SPAN></div>
   </body>
</html>